Repository MarioGabIFP/Super_Paco_Bros, pull requests merged in 2022-05, with the labels that each got.

#17 Modelos y Colisiones
  Super Paco Bros/assets/level/Textures/80.png
  Super Paco Bros/assets/level/Tiled/1.tmx
  Super Paco Bros/assets/level/Tiled/1.tsx
  Super Paco Bros/core/src/main/java/com/paco/core/controller/Initializer.java
  Super Paco Bros/core/src/main/java/com/paco/core/controller/Orchestrator.java
  Super Paco Bros/core/src/main/java/com/paco/core/controller/ScreenController.java
  Super Paco Bros/core/src/main/java/com/paco/core/controller/controls/Action.java
  Super Paco Bros/core/src/main/java/com/paco/core/controller/controls/Contact.java
  Super Paco Bros/core/src/main/java/com/paco/core/controller/controls/types/ModelActions.java
  Super Paco Bros/core/src/main/java/com/paco/core/gui/Graphics.java
  Super Paco Bros/core/src/main/java/com/paco/core/gui/elements/Base.java
  Super Paco Bros/core/src/main/java/com/paco/core/gui/elements/Form.java
  Super Paco Bros/core/src/main/java/com/paco/core/gui/elements/Models.java
  Super Paco Bros/core/src/main/java/com/paco/core/gui/frameable/Level.java
  Super Paco Bros/core/src/main/java/com/paco/core/gui/frameable/Map.java
  Super Paco Bros/core/src/main/java/com/paco/core/gui/frameable/Menu.java
  Super Paco Bros/core/src/main/java/com/paco/core/models/Brick.java
  Super Paco Bros/core/src/main/java/com/paco/core/models/Ground.java
  Super Paco Bros/core/src/main/java/com/paco/core/models/ModelBase.java
  Super Paco Bros/core/src/main/java/com/paco/core/models/Pipe.java
  Super Paco Bros/core/src/main/java/com/paco/core/models/Player.java
  Super Paco Bros/core/src/main/java/com/paco/core/models/Pointer.java
  Super Paco Bros/core/src/main/java/com/paco/core/models/elements/LevelModel.java
  Super Paco Bros/core/src/main/java/com/paco/core/models/elements/MenuModel.java
  Super Paco Bros/core/src/main/java/com/paco/core/models/elements/ModelFunctions.java
  Super Paco Bros/lwjgl3/src/main/java/com/paco/core/lwjgl3/Lwjgl3Launcher.java
  tiled proyects/Menu.tiled-session
Labels: enhancement

#18 Brad2
  Super Paco Bros/assets/powerUps/tiles/pacohou.png
Labels: duplicate, enhancement

#19 añadir clase beer
  .classpath
  .gitignore
  .project
  Super Paco Bros/core/src/main/java/com/paco/core/models/Beer.java
Labels: enhancement

#20 Agregar efectos de sonido
  Super Paco Bros/assets/music/Bigger.mp3
  Super Paco Bros/assets/music/Coin.mp3
  Super Paco Bros/assets/music/Jump.mp3
  Super Paco Bros/assets/music/Lose.mp3
  Super Paco Bros/assets/music/Win.mp3
  Super Paco Bros/core/src/main/java/com/paco/core/gui/elements/FX.java
Labels: enhancement

#21 cerveza juego nueva
  .idea/Super_Paco_Bros.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  Super Paco Bros/assets/powerUps/cerveza_juego.png
Labels: enhancement

#23 Agrego mapa
  Super Paco Bros/assets/level/Tiled/2.tmx
Labels: enhancement

#24 Mario
  Super Paco Bros/assets/level/Tiled/2.tmx
  Super Paco Bros/core/src/main/java/com/paco/core/models/Brick.java
Labels: enhancement

#25 Agrego tiles Paco
  Super Paco Bros/assets/player/Tiles/pixil-frame-0 (1).png
  Super Paco Bros/assets/player/Tiles/pixil-frame-0 (2).png
  Super Paco Bros/assets/player/Tiles/pixil-frame-0 (3).png
  Super Paco Bros/assets/player/Tiles/pixil-frame-0 (4).png
  Super Paco Bros/assets/player/Tiles/pixil-frame-0 (5).png
  Super Paco Bros/assets/player/Tiles/pixil-frame-0 (6).png
  Super Paco Bros/assets/player/Tiles/pixil-frame-0 (7).png
  Super Paco Bros/assets/player/Tiles/pixil-frame-0.png
Labels: enhancement

#27 + Doc
  doc/uml/activities/Super Paco Bros - Diagrama de Actividades.png
  doc/uml/activities/Super Paco Bros - Diagrama de Actividades.vpd
  doc/uml/class/UML_0.0.1_Beta.png
  doc/uml/class/classD_V_0.0.1_Beta.ump
  doc/uml/sequence/Diagrama de secuencia.png
  doc/uml/sequence/Diagrama de secuencia.vpd
Labels: documentation

#28 +doc
  doc/uml/activities/Super Paco Bros - Diagrama de Actividades.png
  doc/uml/activities/Super Paco Bros - Diagrama de Actividades.vpd
Labels: documentation
